name: bb3_matchup
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - pip
  - matplotlib
  - pip:
    - pandas==1.3.3
    - parse==1.19.0
    - statsmodels==0.13.0  # for ts seasonal decomp
    - pytest==6.2.5
    - plotly==5.4.0
